import type { Metadata } from "next";
import { cookies } from "next/headers";
import { Inter } from "next/font/google";
import "./globals.css";
import { Navbar } from "@/components/organims/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	const cartId = cookies().get("cartId")?.value;
	return (
		<html lang="en">
			<body className={inter.className}>
				<div className="min-h-screen bg-white">
					<Navbar cartId={cartId} />
					<div className="mx-auto max-w-2xl px-4 py-16 sm:px-6 sm:py-24 lg:max-w-7xl lg:px-8">
						{children}
					</div>
				</div>
			</body>
		</html>
	);
}
